### PR TITLE
[docker] refs #111 - Disable builds for ARM v5 and v7

### PR DESCRIPTION
**Pull request by olemis**
Temporary solution for #111 

Changes :

- Enable the builds for versions supported by `alpine` image
- Disable the rest

### CODE REVIEW

**Comment by olemis** [comment]
@stdevMauricio pls take a look into this issue

**Comment by olemis** [comment]
This is issue has been solved . Using `busybox` as base image now .

**Comment by some4** [comment]
current U-BOOT will not compile with ARM v6 and below

**Comment by olemis** [comment]
> current U-BOOT will not compile with ARM v6 and below

@some4 if that's the case then create another issue to work on it . This PR was aimed at fixing  #111 . Since the problem was caused by using `alpine` as base image and we are not using it now , no further work needed in here .

**Comment by some4** [comment]
@olemis Oh I meant to note that it's incompatible--v6 and below won't work with upstream there's nothing we can do about it

**Pull request closed without merging**
