### PR TITLE
Node list view implemented designs

### PR DESCRIPTION
**Pull request by IvanPayan**

### CODE REVIEW

**Comment by therealssj** [comment]
think you could attach some screenshots of how it looks?
thanks for your work! :D

**Review by mahansky — APPROVED** [review]

**Comment by mahansky** [comment]
@IvanPayan I think it would be better to use Material Icons instead of adding custom SVGs. Material Icons are already installed in the project.

**Comment by IvanPayan** [comment]
captura de pantalla 2018-07-18 a les 15 35 46

@therealssj this is a screenshot of the node list view :)

**Comment by IvanPayan** [comment]
@mahansky okey! I'll use the Material Icons. For those icons that do not exist in the Material Icons collection, shall we use the SVG or change it to a Material Icon that looks similar?

**Comment by mahansky** [comment]
Similar material icon

**Pull request merged**
