### PR TITLE
[ROUTING] Changes to transport.Transport interface.

### LINKED ISSUE #469: [ROUTING] Changes to transport.Transport interface.
**The current problem**

The ability to differentiate between local/remote edges is very important when we use `transport.Transport`. The current solution of using `transport.Edges()` method is not elegant and results in additional boilerplate.

**Tasks**
- [ ] Replace `Edges() [2]cipher.PubKey` with `LocalPK() cipher.Pubkey` and `RemotePK() cipher.Pubkey` in `transport.Transport` definition.
- [ ] Improve methods that regards determining transport ID.

### PR DESCRIPTION
**Pull request by nkryuchkov**
Closes #469 

Changes:
- Replace `Edges()` method with `LocalPK()` and `RemotePK()` in `transport.Transport` interface.

### CODE REVIEW

**Comment by evanlinjin** [comment]
@nkryuchkov From a glance, it looks good. However, we need to resolve the conflicts.

**Comment by nkryuchkov** [comment]
@evanlinjin It's still WIP because some tests fail. I need to investigate why and fix.

**Comment by nkryuchkov** [comment]
@evanlinjin I've fixed the tests failures and resolved the conflicts. I think it's ready for review.

**Comment by evanlinjin** [comment]
I'm going to put this PR on hold for the time being. Really depends if these changes gets approved or not: https://github.com/skycoin/skywire/issues/488

**Review by evanlinjin — APPROVED** [review]

**Pull request merged**
