### PR TITLE
Cleanup: move pathutil from /internal/pathutil to /pkg/util/pathutil

### PR DESCRIPTION
**Pull request by atang152**
Moved /internal/pathutil to /pkg/util/pathutil as per https://github.com/skycoin/skywire-updater/pull/7#pullrequestreview-227368978. Please let me know if this is correct. Thank you.

### CODE REVIEW

**Comment by ayuryshev** [comment]
You created PR directly non-related with any issue?
Am I correct?

Closes: #296

**Review by ayuryshev — APPROVED** [review]

**Comment by atang152** [comment]
> You created PR directly non-related with any issue?
> Am I correct?
> 
> Closes: #296

Hi Ayu. Yes, it's not related to any issues on hand. Evan mentioned to move it from internal to pkg as per the code review. Sorry, I will create an issue next time first. Thank you.

**Review by ivcosla — COMMENTED** [review]
Looking good!

**Comment by evanlinjin** [comment]
@atang152 @ayuryshev 

In the future, we can just reference the related issue in `skycoin/skywire-updater`, instead of creating a separate issue in `skycoin/skywire`.

**Pull request merged**
