### PR TITLE
change mesh/node

### PR DESCRIPTION
**Pull request by ZSM5J**

### CODE REVIEW

**Review by gz-c — CHANGES_REQUESTED** [review]
Remove the .idea/ folder

**Comment by gz-c** [comment]
Can you put a better title for the pull request and for the commit message?

**Comment by ZSM5J** [comment]
-I write new library called "signal", and integrate it to mesh/node, now this app can connect to viscript, and viscript can send ping, res_usage, shutdown command to app.

**Comment by gz-c** [comment]
You need to update the dependencies. See the README file

**Comment by ZSM5J** [comment]
is it right now?

**Comment by gz-c** [comment]
No, you need to do `dep prune`
But also, why is `github.com/skycoin/skywire` added to `Gopkg.toml`? That should not be there

**Comment by ZSM5J** [comment]
Gopkg.toml is the same as skywire's file at this moment, check:
https://github.com/ZSM5J/skywire/blob/master/Gopkg.toml

**Comment by gz-c** [comment]
I mean `Gopkg.lock`

**Comment by ZSM5J** [comment]
can you help me, what do I need add with dep. Only file is changed by me is: 
https://github.com/ZSM5J/skywire/blob/master/cmd/mesh/node/node.go
I import "github.com/skycoin/viscript/signal" and change 2 lines.

**Comment by vyloy** [comment]
I have refactored signal library, so this pull request can be closed

**Pull request closed without merging**
