### PR TITLE
Fix messaging data race 354.

### LINKED ISSUE #354: Data races on exit of Skywire-nodes
# How to reproduce bug

1. Start 3 skywire-nodes: 
- NodeA with thereallssh app
- intermediary NodeB without apps
- NodeC with therealssh-client app
2. Add transports from NodeA and NodeC to NodeB
3. Start ssh communication. E.g. `therealssh-cli $PK_A "echo A"` (or `cat` a file, `ls`, `tree`, etc)
4. Kill nodes during proccess

With high probability data races will be on one or two of nodes.

Sometimes data race is followed with `panic: send on closed channel` and sometimes not.

Attached logs:
- nodeB.log and nodeC.log - are from one run
- nodeA.log - from another

[nodeC.log](https://github.com/skycoin/skywire/files/3186281/nodeC.log)
[nodeB.log](https://github.com/skycoin/skywire/files/3186282/nodeB.log)
[nodeA.log](https://github.com/skycoin/skywire/files/3186283/nodeA.log)

### PR DESCRIPTION
**Pull request by evanlinjin**
closes #354

### CODE REVIEW

**Comment by ivcosla** [comment]
Using that PR and integration tests for ssh I have been able to see the data race on the 3 nodes, however it might take more than one run to see the data race appear in A or C, while it has appeared on every run for node B.

[nodeA.log](https://github.com/skycoin/skywire/files/3206816/nodeA.log)
[nodeB.log](https://github.com/skycoin/skywire/files/3206818/nodeB.log)
[nodeC.log](https://github.com/skycoin/skywire/files/3206814/nodeC.log)

**Comment by ayuryshev** [comment]
So integration tests not passed?

**Comment by ivcosla** [comment]
> So integration tests not passed?

Not passed.

**Comment by ivcosla** [comment]
I realized that I had the line for replacing skywire commented in services go.mod. I have re-tested the branch and indeed the DATA RACES are gone.

I think it's safe to merge this PR, then apply changes from https://github.com/skycoin/skywire/pull/369 once tests are passing.

**Review by ivcosla — APPROVED** [review]

**Review by ayuryshev — APPROVED** [review]
I observe that data races on all nodes are eliminated

**Pull request merged**
