### PR TITLE
Renaming to (hyper)visor

### LINKED ISSUE #452: Renaming to (hyper)visor
It was observed that Synth uses the words visor and hypervisor for what is now referred to as App Node (or node in code) and Manger Node. 

- [x] rename node to visor

- [x] rename manager node to hypervisor

### PR DESCRIPTION
**Pull request by nkryuchkov**
Closes #452.

Changes:
- Rename `skywire-node` to `skywire-networking-node`
- Rename `app-manager` to `visor`
- Rename `manager-node` to `hypervisor`

NOTE: production configs need to be reviewed and updated before deployment.

### CODE REVIEW

**Comment by jdknives** [comment]
@evanlinjin @nkryuchkov I did not consider the case of the setup node for this renaming actually. Technically it should be renamed to Setup Visor. But I am not sure this terminilogy makes sense to you.

**Comment by nkryuchkov** [comment]
@jdknives I have a similar thought while working on the PR. Without it, the naming convention looks inconsistent. I agree and think it's a good name.

**Comment by evanlinjin** [comment]
This is what I got from the conversation from Brandon:

| Old Names | New Names |
| -- | -- |
| `skywire-node` | `skywire-networking-node` |
| `app-manager` | `visor` |
| `manager-node` | `hypervisor` |
| `setup-node` | `setup-node` |

**Comment by evanlinjin** [comment]
@nkryuchkov Sorry for being a hassle. But can you make the following changes -as per request from Brandon.

1. `skywire-node` is to be called `skywire-visor`.
2. Module `/pkg/node` is to be called `/pkg/visor`.
3. `AppManager` should retain it's original name.

**Comment by nkryuchkov** [comment]
@evanlinjin Sure. I've made them. Could you please have a look again? Does anything else need to be renamed?

**Review by jdknives — APPROVED** [review]
Seems fine to me.

**Comment by evanlinjin** [comment]
@nkryuchkov The changes made here should not break whatever is in `skywire-services`. Please make an associated PR there. Thanks!

**Review by ivcosla — APPROVED** [review]
Looks good to me, but there are some conflicts to solve.

**Review by Darkren — APPROVED** [review]
Seems great to me

**Pull request merged**
