### PR TITLE
Delete messaging and use 'dmsg' repo.

### LINKED ISSUE #451: [DMSG] Delete messaging and use 'dmsg' repo.

### PR DESCRIPTION
**Pull request by nkryuchkov**
Closes #451 

 Changes:	
-	Switched from `github.com/skycoin/skywire/pkg/{dmsg, messaging, messaging-discovery}` to `github.com/skycoin/dmsg`
-	Created a wrapper for `github.com/skycoin/dmsg` in `github.com/skycoin/skywire/pkg/transport/dmsg`
-	Deleted `github.com/skycoin/skywire/pkg/{dmsg, messaging, messaging-discovery}`

### CODE REVIEW

**Review by ivcosla — APPROVED** [review]
Looks good

**Comment by evanlinjin** [comment]
Because `watercompany/skywire-services` depends on this repo, we also need to give that an update before merging this! Please make this a priority.

**Comment by jdknives** [comment]
@evanlinjin @nkryuchkov I thought this was ready for review already.

**Review by ayuryshev — APPROVED** [review]
From my experiments - everything works

**Comment by evanlinjin** [comment]
> @evanlinjin @nkryuchkov I thought this was ready for review already.

It doesn't work with `watercompany/skywire-services` interactive tests because of some renaming of modules.

**Review by evanlinjin — APPROVED** [review]

**Pull request merged**
