### PR TITLE
Fix linter errors

### PR DESCRIPTION
**Pull request by nkryuchkov**
Right now, TravisCI builds fail for all pull requests on `mainnet-milestone` branch because it contains linter errors. This PR fixes the errors that break builds.

### CODE REVIEW

**Review by evanlinjin — COMMENTED** [review]
@nkryuchkov I'm curious on the reasoning behind logging error instead of ignoring them with a `nolint` comment? For closing connections, sometimes the connection is already closed, and we just need to ensure that they are closed so the error does not need to be handled.

**Comment by nkryuchkov** [comment]
@evanlinjin I wanted us to have more control of what's going on in tests, however, I had no thought that connections might be already closed. What do you think of checking if `err` contains either `nil` or an `already closed` error? I don't like linter suppression and I think it might be more clear if we could handle errors this way.

**Comment by evanlinjin** [comment]
> @evanlinjin I wanted us to have more control of what's going on in tests, however, I had no thought that connections might be already closed. What do you think of checking if `err` contains either `nil` or an `already closed` error? I don't like linter suppression and I think it might be more clear if we could handle errors this way.

Okay good point and good solution. Let's do it that way then. Please make relevant changes.

**Review by Darkren — APPROVED** [review]
Feels like a good job to me

**Pull request merged**
