### PR TITLE
Implement module for obtaining a user's response.

### PR DESCRIPTION
**Pull request by nkryuchkov**
Closes: #262 

Done:
- `InputGrabber`
- `WebsocketGrabber`
- `MultiGrabber`

Partially done:
- Documentation

To do:
- Tests

Won't be done:
- `CommandLineGrabber`

### CODE REVIEW

**Comment by nkryuchkov** [comment]
Done:
- `InputGrabber`
- `WebsocketGrabber`
- `MultiGrabber`
- Documentation
- Tests

Won't be done:
- `CommandLineGrabber`

**Review by evanlinjin — APPROVED** [review]
Looks good!

**Comment by evanlinjin** [comment]
@nkryuchkov can you please fix the merge conflicts and then we can merge. Thanks!

**Comment by nkryuchkov** [comment]
@evanlinjin Yes, sure, thank you for the review. Should I update the versions of `golang.org/x/crypto` and `golang.org/x/net` or leave them as they are in `mainnet-dev`?

**Comment by nkryuchkov** [comment]
`golang.org/x/crypto` and `golang.org/x/net` are updated

**Pull request merged**
